### ISSUE TITLE
Bumping h3ron-sys

### ISSUE THREAD

**Issue by grim7reaper** [nmandery/h3ron#73]
Hi,

H3 recently merged the following PR: https://github.com/uber/h3/pull/749

I've updated h3o with the new values, but since I've some test running against H3 through `h3ron-sys`, they are now failing because I'm comparing against an old version.

Would it be possible to bump the commit targeted by `h3ron-sys` and release a new version?

**Comment by nmandery** [comment]
Hi, sure - understandable. It also has been a while since the last release here.

The last H3 release is v4.1.0, which I am currently using in the main branch. The PR you linked is not yet available in a release by H3 itself yet (https://github.com/uber/h3/compare/v4.1.0...master), so I am a bit reluctant to create a new `h3ron-h3-sys` release based on a unreleased upstream version. 

In case you really need this urgently, we can do a release of course ;)

**Comment by grim7reaper** [comment]
No hurry, this can wait 🙂

**Comment by grim7reaper** [comment]
In the end, I've wrote my own tests that doesn't rely on H3 (which I should do anyway, it nice to have a differential test suite but I should also have my own independent one) by reimplementing the computation myself 🙂

**Comment by nmandery** [comment]
Alright, so this has been decoupled now - which is great. 
I will keep checking uber/h3 every once in a while for new releases.
